[theme]
primaryColor = "#0f9d58"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e8eef2"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
maxUploadSize = 200
enableXsrfProtection = true
